### ISSUE TITLE
No details show up in new "Special Effects"  tab

### ISSUE THREAD

**Issue by asimone** [bitkiller0/SIFToolkit#1]
For release 0.1.3

Console gives a missing file error and Special Effects details do not show up in the tab. Screenshot shows Tidy5e, but vanilla 5e sheet doesn't appear to work either. See screenshot below.

![Screenshot 2021-07-20 184803](https://user-images.githubusercontent.com/575279/126409813-22f7aed6-7107-40eb-8410-92d1b4529f06.png)

**Comment by asimone** [comment]
Here's a video capture with console errors: https://www.dropbox.com/s/adjnoie6xn0qro5/ItemSheet_handlebar%20error.mp4?dl=0

Error:
```
foundry.js:3587 Uncaught (in promise) Error: ENOENT: no such file or directory, open '/foundry-data/Data/modules/SIFToolkit/templates/ItemSheet.handlebars'
    at f.<anonymous> (foundry.js:3587)
    at f.value (socket.js:305)
    at f.value (socket.js:228)
    at y.r.emit (index.js:145)
    at y.value (typed-events.js:59)
    at y.value (manager.js:214)
    at n.r.emit (index.js:145)
    at n.value (index.js:120)
    at y.value (manager.js:206)
    at p.r.emit (index.js:145)
```

As I noted above, I've try the same thing on a separate world with no other add-ons enable, so I don't _think_ it's a conflict.

**Comment by dirusulixes** [comment]
Same here. In my case I'm running it with DND5e and the offending line was https://github.com/bitkiller0/SIFToolkit/blob/d94aff3b509e7cefb6e0fff57c386dae5321cb8f/scripts/dnd5e/itemSheet.js#L37

changing the path to all lowercase fixed it:
`            let renderedTemplate = await renderTemplate("./modules/siftoolkit/templates/itemsheet.handlebars",`

**Comment by bitkiller0** [comment]
Should be corrected.  There have been instances where uninstall reinstall are necessary due to caching issues.
