### ISSUE TITLE
[BUG] Error on spell after placing template on the canvas

### ISSUE THREAD

**Issue by DarKDinDoN** [bitkiller0/SIFToolkit#10]
Hello,

System: 5e 1.4.1
FVTT 0.8.8
SIF 0.1.20
SimpleCalendar 1.3.8
BetterRolls5e 1.5.6

After placing a spell template on the canvas, I get this error:
![image](https://user-images.githubusercontent.com/1687854/127378304-4474e645-c08c-4ebb-9c21-c47fd435b12f.png)

And the template is not handled by SIF

**Comment by bitkiller0** [comment]
At this time, I am not looking into any errors that occur while Better
rolls is installed.

**Comment by DarKDinDoN** [comment]
@bitkiller0 this error occurs without BetterRolls5e activated.
With a brand-new spell, not modified by BetterRolls5e.

**Comment by bitkiller0** [comment]
Gotcha. I'll look into this one too.

**Comment by bitkiller0** [comment]
corrected in 0.1.21

**Comment by DarKDinDoN** [comment]
Thx!
