### ISSUE TITLE
[QUESTION] Unmanaged template action

### ISSUE THREAD

**Issue by DarKDinDoN** [bitkiller0/SIFToolkit#11]
Hello,

Would you mind explaining to me what this setting does?
![image](https://user-images.githubusercontent.com/1687854/127466182-0c89effd-26d4-4e59-a37f-d51906e5d899.png)

I don't see any prompt when I manually create a template on the canvas and advance one turn/round in the combat tracker.

EDIT: tested **without** BetterRolls.

**Comment by bitkiller0** [comment]
Yep.  That section of code got clipped.  I'll add it back in.  If you'd like to see what it does, in action, create a measured template manually.  Then, from the console, enter: SIFT.utils.manageUnmanaged();

**Comment by bitkiller0** [comment]
fixed in 0.1.25.  This version should prompt the DM to apply template settings to non-managed templates.
