### ISSUE TITLE
Does not provide a valid manifest file

### ISSUE THREAD

**Issue by QuantumBreed** [bitkiller0/SIFToolkit#16]
Get the error "The request to https://github.com/bitkiller/SIFToolkit/raw/master/module.json did not provide a valid manifest file" upon attempt to update. Using most stable version of foundry.

**Comment by bitkiller0** [comment]
Which version of SIFT are you on?  This problem was fixed some time ago.

**Comment by bitkiller0** [comment]
What version is currently installed?

**Comment by QuantumBreed** [comment]
SIFT? I am on version 8.8 of Foundry VTT with the newest version of DnD5e 1.4.1 though this started on version 1.3 of DnDe5.

**Comment by QuantumBreed** [comment]
NVM tired and just realized the acronym. I am on version 0.1.14.

**Comment by bitkiller0** [comment]
Understood. I was having that problem for a while, and it has been fixed. You may need to uninstall and reinstall for it to take effect however.

**Comment by QuantumBreed** [comment]
okay thank you for the help
