### ISSUE TITLE
Issues with PF2 time

### ISSUE THREAD

**Issue by apoapostolov** [bitkiller0/SIFToolkit#17]
Placed template from a spell like Grease with 1 minute duration. Changing time forward via SmallTime, SimpleCalendar does not lead to the spell disappearing its template.

**Comment by bitkiller0** [comment]
Circling back to this one.  I looked at the spell "Grease".  It does not appear to have an area associated with it.  How are you placing a template for it?

**Comment by bitkiller0** [comment]
Following up on this one.  Were you able to review the spell Grease?  Does it have an area associated with it?  Also, when you place the template, the border should be color coded; what color does it change to and which template type does that correspond to?
