### ISSUE TITLE
Freeform templates are considered tied to the last spell cast

### ISSUE THREAD

**Issue by Fraxinus1753** [bitkiller0/SIFToolkit#19]
Thanks for this very helpful module! I don't know if this is a feature or a bug, but when I place a freeform template, it inherits all the metadata of the last spell cast (and thus replaces it if it was a concentration spell). 

This can be very helpful as some of Foundry's pre-entered templates might need to be changed on the fly (e.g. for wall spells that can be cast as domes). However, it would be very nice to have an option to disable this, since the result is that it's impossible to draw a freeform template unrelated to any spell previously cast with this module enabled.

**Comment by bitkiller0** [comment]
I propose a new button on the Measurement Controls that will clear current effects data so that it will not be used on subsequent templates (until a new "spell" is "cast").  This would still allow for re-use but also placing a freeform template without reuse albeit requiring an extra click.

**Comment by Fraxinus1753** [comment]
That would be great, thanks!

**Comment by bitkiller0** [comment]
Implemented in 0.1.29
