### ISSUE TITLE
Module not activating

### ISSUE THREAD

**Issue by ctbritt** [bitkiller0/SIFToolkit#2]
Have turned off all modules except SIFToolkit, libwrapper and lib-colorsettings and the Special Effects tab shows up on a spell, but tab is blank. 
<img width="567" alt="Screen Shot 2021-07-22 at 4 12 46 PM" src="https://user-images.githubusercontent.com/4516034/126703468-fe1a92c4-3830-4704-870d-9883cb1946c5.png">

**Comment by ctbritt** [comment]
Ah, interesting. It's installing v1.11 instead of the latest v1.2 when I install from the foundry module tab.

**Comment by ctbritt** [comment]
ok. none of your links are working. 
https://github.com/bitkiller0/SIFToolkit/raw/master/module.json << doesn't work, 404
https://github.com/bitkiller0/SIFToolkit/archive/0.1.14.zip << 404 error

**Comment by bitkiller0** [comment]
I understand. Unfortunately I am nowhere near my computer right now. Also
unfortunately, I have been having major code editor and repository commit
issues all day. I plan to have a fix up tonight. I will respond as soon as
that is done.

**Comment by bitkiller0** [comment]
Identified a new cause for this bug.  It's patched in 0.1.15.  Please update and let me know if this is fixed for you.  

Unfortunately, due to manifest issues, an uninstall/reinstall may be necessary.

**Comment by DarKDinDoN** [comment]
Same error with the latest version

![image](https://user-images.githubusercontent.com/1687854/126848992-acbb1e83-fd95-443c-ab69-b345dbe2894a.png)

**Comment by bitkiller0** [comment]
Is this local or hosted?

**Comment by bitkiller0** [comment]
Issue is confirmed working in Forge with v0.1.17.   Please confirm.

**Comment by DarKDinDoN** [comment]
@bitkiller0 hosted, ubuntu.
Still not working, still have issues

**Comment by DarKDinDoN** [comment]
@bitkiller0 updated to latest version. Working ;)
