### ISSUE TITLE
[Suggestion] Remove SIFT popup for Players

### ISSUE THREAD

**Issue by M0nk3yy** [bitkiller0/SIFToolkit#20]
Currently players logging in are greeted with the SIFT popup, which I find is mostly irrelevant for them.

If it can't be removed for players, I would suggest an option to "Never see this again", as currently fairly frequent updates mean they are shown the popup repeatedly.

**Comment by Varriount** [comment]
I despise pop-ups like this - 90% of the time they are unneeded, and half the time they show up for both players and GMs (when they have absolutely zero relevance to players). I don't want to update my modules, and suddenly have myself or my players clicking through 20 different windows.

**Comment by bitkiller0** [comment]
Removed display of pop-up for non-gm users in 0.1.29.
