### ISSUE TITLE
Transparent bar used in Special Effects tab in ItemSheet bleeding over with Tidy5eSheet module enabled.

### ISSUE THREAD

**Issue by Brimcon** [bitkiller0/SIFToolkit#29]
I mentioned this in Foundry's Module Troubleshooting discord channel but it seems the Special Effects creates a Tidy5e Sheet bar that bleeds over into various other bits of the canvas and character Sheet if Tidy5e sheet is enabled with SIF 0.2.4

![image](https://user-images.githubusercontent.com/7198283/138136260-ae1005f8-99c3-47c5-ad61-54ffa633a85b.png)
This is with the default Item Sheet. 

And here's the issue in question: https://cdn.discordapp.com/attachments/722566083499786352/900420577599324270/unknown.png

This did not occur with previous versions of SIF.

**Comment by bitkiller0** [comment]
This should be fixed in 0.2.5.  All SIFT custom styles have been reformatted to only be called if the class .siftoolkit is present.  please confirm.

**Comment by Brimcon** [comment]
It is fixed! Thank you!
