### ISSUE TITLE
Remaining template duration: Unknown seconds

### ISSUE THREAD

**Issue by OzBezerius** [bitkiller0/SIFToolkit#3]
I tried this module before in my local foundry 8.8 and it worked, but i installed it in the forge 8.8, and no matter how I put the template(manually or spells) the duration is unknown.
![image](https://user-images.githubusercontent.com/25015102/126797015-b017b1d1-66a7-49de-bf91-504236c9a578.png)

I am getting this error when i enter the game too. 
![image](https://user-images.githubusercontent.com/25015102/126796906-2a1c2ed2-8197-41b4-85c1-57f5e4df776f.png)

**Comment by bitkiller0** [comment]
Please update to the latest version: 0.1.18.  This version corrects the error located in your console.  This may correct additional issues.  Please verify if all issues are corrected and/or advise of any remaining issues.  When doing so, please provide foundry/system/module versions.  Please verify that you are receiving these issues with no other mods installed.

**Comment by bitkiller0** [comment]
Is there an update on this issue?  I would like to close.

**Comment by OzBezerius** [comment]
Yes, i tried it again and it seems to work now, tried it without other modules too.
