### ISSUE TITLE
Manifest doesn't include link to the online manifest file for updating

### ISSUE THREAD

**Issue by apoapostolov** [bitkiller0/SIFToolkit#4]
![image](https://user-images.githubusercontent.com/4083812/126819413-284aade0-8b9b-4048-82e3-46194a7d23ab.png)

**Comment by bitkiller0** [comment]
manifest updated with new URL.   Please confirm fix.

**Comment by apoapostolov** [comment]
all good in latest release

**Comment by Cubius** [comment]
Having the same error for a few days now:
![image](https://user-images.githubusercontent.com/15717384/127135481-e86d7330-7d09-4524-9bb3-26e7b624db62.png)

**Comment by bitkiller0** [comment]
Due to an earlier error, it may be necessary to uninstall and reinstall. If you are still having problems after uninstall and reinstall, please inform of your version.
