### ISSUE TITLE
[Feature request] Scale animation with template

### ISSUE THREAD

**Issue by DarKDinDoN** [bitkiller0/SIFToolkit#6]
Hello,

Trying to use a jb2a animation on a line template to simulate a fire wall.
Problem is that the fire animation is much smaller that the template

![image](https://user-images.githubusercontent.com/1687854/126867156-deae8148-cad6-41dd-9f5c-2d6b604561c3.png)

**Comment by bitkiller0** [comment]
This SHOULD already be happening.  Which jb2a animation are you trying to use, and which spell are you attempting to apply it to?  Also, which system is this for?

**Comment by DarKDinDoN** [comment]
System: 5e 1.3.6
FVTT 0.8.8
SIF 0.1.18
SimpleCalendar 1.3.8
BetterRolls5e 1.5.6

Link to the exported spell: https://we.tl/t-3ymEcg5G44

**Comment by DarKDinDoN** [comment]
@bitkiller0 Tested without BetterRolls.
This is not an issue related to BetterRolls.

**Comment by bitkiller0** [comment]
It looks like I did, in fact, have some hard-coded (5)s, for Imperial system.  I've made a couple of changes.  Please let me know if this fixes the scaling issues in 0.1.23.

**Comment by bitkiller0** [comment]
Confirmed corrected.
