### ISSUE TITLE
[BUG] Spell templates without damages' formula don't work as intended

### ISSUE THREAD

**Issue by DarKDinDoN** [bitkiller0/SIFToolkit#7]
Hello,

In 5e, if the user attempt to place a spell template without any damages' formula declared, the template won't be parsed by SIF Toolkit (no duration, no auto removal, etc.)

EDIT: using BetterRolls5e

**Comment by bitkiller0** [comment]
Is this issue different from Issue #5?

**Comment by DarKDinDoN** [comment]
@bitkiller0 yes, just tested it. If I add a damage formula to the item or consumable, the template is correctly handled by SIF

**Comment by DarKDinDoN** [comment]
Confirmed as an issue tied to BetterRolls

**Comment by DarKDinDoN** [comment]
Attempt to fix this: https://github.com/bitkiller0/SIFToolkit/pull/12
