### ISSUE TITLE
[BUG] "Ignore spell duration" doesn't work

### ISSUE THREAD

**Issue by DarKDinDoN** [bitkiller0/SIFToolkit#8]
Hello,

Assuming a spell with a 1 minute duration and the checkbox "Ignore spell duration" checked.
Once the template is placed, the duration of the template remains 1 minute. And the template won't be deleted after 1 turn.

EDIT: using BetterRolls5e

**Comment by bitkiller0** [comment]
Please provide sample console output during this event.

**Comment by bitkiller0** [comment]
Please confirm system/module version numbers.  Also, are you using simple calendar or SIFT for time processing?  Is Simple Calendar installed?  Please verify that "Instantaneous Spell Fade duration" is set to 0, in settings.  Please provide the name of the spell tested with.  Thanks!

**Comment by DarKDinDoN** [comment]
System: 5e 1.3.6
FVTT 0.8.8
SIF 0.1.18
SimpleCalendar 1.3.8
BetterRolls5e 1.5.6

Link to the exported spell (excuse the French fields :)): https://we.tl/t-PtdWpMVnCm

Console output (nothing relevant I think)
![image](https://user-images.githubusercontent.com/1687854/127154390-02c62b54-5db4-4054-a689-01cc6ee7360c.png)

Settings
![image](https://user-images.githubusercontent.com/1687854/127154462-1107e06a-6214-4d10-9082-74ae0546ee9a.png)

**Comment by DarKDinDoN** [comment]
@bitkiller0 Tested without BetterRolls.
This is not an issue related to BetterRolls.

**Comment by bitkiller0** [comment]
corrected in 0.1.22

**Comment by DarKDinDoN** [comment]
Working! Thx :)

**Comment by DarKDinDoN** [comment]
@bitkiller0 tested it in 0.1.23.
I don't think it's working as intended.

Settings are the same as in  the screenshot in the previous comment.
1. Start a fight (round 1)
2. Cast a spell and place a template with the checkbox "Ignore Spell Duration (remove immediately)"
3. Once the turn is over and the next combatant is playing, the template is still there
4. Following round (round 2), the template is still there
5. Start of round 3, the template is finally deleted from the canvas

It should be deleted right after the turn is over, right?
