### ISSUE TITLE
Error with Hooks at prepareSIFT

### ISSUE THREAD

**Issue by ravingdragoon** [bitkiller0/SIFToolkit#9]
I am getting the following error every time I launch Foundry with SIFT enabled.
Uncaught (in promise) TypeError: Cannot read property 'getFlag' of null
    at Object.pushItemData (Utils.js:326)
    at Object.clearTemplateData (Utils.js:410)
    at Module.setHooks (Hooks.js:32)
    at prepareSIFT.js:37

Attached is the full error as downloaded from the (F12)Console.
[FoundryVTT Console Error 162722433.txt](https://github.com/bitkiller0/SIFToolkit/files/6874427/FoundryVTT.Console.Error.162722433.txt)

**Comment by bitkiller0** [comment]
Issue corrected in 0.1.18
